# -*- coding: utf-8 -*-
"""Processed Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_9cnzcUqr22w5wzQVkC1IGvXrdv0WCzQ
"""

import pandas as pd
import datetime as dt
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv("Train bank.csv", sep="\,")

data.columns = data.columns.str.replace('"','')

print(data.shape)

print(data.isna().sum())

data = data.dropna()

categorical = ["Job", "Marital.Status", 'Education', 'Contact','Last.Contact.Month','Poutcome']
ordinal = ["Age",'Last.Contact.Day','Campaign','Previous', 'Pdays']
numeric = ["Balance..euros.", 'Last.Contact.Duration']
binary = ["Credit",'Housing.Loan','Personal.Loan']

lista = ["Age","Balance..euros.", 'Last.Contact.Day', 'Last.Contact.Duration','Campaign','Pdays','Previous']
for col in data.columns:
  if col not in lista:
    data[col]=data[col].map(lambda x : x.replace('"',''))
  if col in binary:
    data[col] = data[col].eq("yes").mul(1)

data.to_csv("processtrainbank.csv",index=False)

print(data)
